### ISSUE TITLE
go.opencensus.io is obsolete and archived

### ISSUE THREAD

**Issue by dims** [microsoft/hnslib#10]
https://github.com/census-instrumentation/opencensus-go has been archived since July 2023. Can we please drop its usage from this library?

xref: https://github.com/kubernetes/kubernetes/issues/120276

**Comment by princepereira** [comment]
Sure @dims . Beginning to work on it.

**Comment by princepereira** [comment]
@dims , Is there a alternate proposal for go.opencensus.io from the community

**Comment by dims** [comment]
@princepereira on the [README](https://github.com/census-instrumentation/opencensus-go/blob/master/README.md) the alternative mentioned is [OpenTelemetry](https://opentelemetry.io/) which is awesome because k8s/containerd use otel as well.

**Comment by princepereira** [comment]
@dims , do we have K8s issue for vendoring new hnslib tag.

**Comment by dims** [comment]
@princepereira we don't have one, currently there's a freeze for 1.32, when that gets released we can bump!
